# Generated by Django 5.0 on 2024-04-18 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_auth_status_user_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e3c4ebd-b3f1-4809-9918-17eca15233b1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
